- name: Install | Install dhcp4_server packages
  when: dhcp4_server_use_docker | lower == 'false'
  package:
    name: '{{ dhcp4_server_distro_packages }}'
    state: '{{ dhcp4_server_package_state }}'
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
  - install-apt
  - install-yum
  - install-zypper
